// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8gSJRbKH9uh9LpgMX6U8R8gB747M_Zs',
    appId: '1:771675655192:web:90c6a880ed664c5564476d',
    messagingSenderId: '771675655192',
    projectId: 'tower-of-hanoi-9224d',
    authDomain: 'tower-of-hanoi-9224d.firebaseapp.com',
    storageBucket: 'tower-of-hanoi-9224d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwoNxiV1DgLVnM9ZHiaJ-H2gGJM4ZZKRg',
    appId: '1:771675655192:android:d38cee5ba2902aaa64476d',
    messagingSenderId: '771675655192',
    projectId: 'tower-of-hanoi-9224d',
    storageBucket: 'tower-of-hanoi-9224d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfLbyYbQza5uzqHKElje7SNwTEZfJtRKE',
    appId: '1:771675655192:ios:2e4ad0795205990b64476d',
    messagingSenderId: '771675655192',
    projectId: 'tower-of-hanoi-9224d',
    storageBucket: 'tower-of-hanoi-9224d.appspot.com',
    iosBundleId: 'com.example.hanoiTower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfLbyYbQza5uzqHKElje7SNwTEZfJtRKE',
    appId: '1:771675655192:ios:2e4ad0795205990b64476d',
    messagingSenderId: '771675655192',
    projectId: 'tower-of-hanoi-9224d',
    storageBucket: 'tower-of-hanoi-9224d.appspot.com',
    iosBundleId: 'com.example.hanoiTower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8gSJRbKH9uh9LpgMX6U8R8gB747M_Zs',
    appId: '1:771675655192:web:6b6526bb1fec8da064476d',
    messagingSenderId: '771675655192',
    projectId: 'tower-of-hanoi-9224d',
    authDomain: 'tower-of-hanoi-9224d.firebaseapp.com',
    storageBucket: 'tower-of-hanoi-9224d.appspot.com',
  );
}
